metaconfig:
  name: teacher-tinyimagenet-resnet32
  expt: teacher
  path: ./logs/teacher/
dataset:
  name: TinyImageNet
  kwargs:
    init_augmentations:
      train: >-
        eval:transforms.Compose([
          transforms.RandomCrop(size=[64, 64], padding=8),
          transforms.RandomHorizontalFlip(),
        ])
  image_dim: [3, 64, 64]
  num_classes: 200
  onehot_label: false
  split_remap:
    val: test
dataloader:
  ddp: true
  ddp_kwargs:
    shuffle:
      train: true
      val: false
  batch_size:
    train: 128
    val: 1024
  num_workers: 4
models:
  teacher:
    Class: eval:ResNet_CIFAR
    kwargs:
      input_dim: [3, 64, 64]
      num_classes: 200
      depth: 32
      skip_option: A
optim:
  num_epochs: 200
  opt_T:
    Class: eval:torch.optim.SGD
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
  sch_T:
    Class: eval:torch.optim.lr_scheduler.MultiStepLR
    kwargs:
      milestones: [100, 150]
      gamma: 0.1
